### ISSUE TITLE
http 상태 코드가 조금 아쉽습니다

### ISSUE THREAD

**Issue by fnrkp089** [dntjd960403/4week-project#1]
https://github.com/dntjd960403/4week-project/blob/612d75574f393ebe4945fb3ae5aadf2bd35045da/routes/posts.js#L44

200번대는 요청이 성공적으로 완료되었다는 의미이지만
포스트를 새로 생성햇다는건 
201번 status코드가 더 낫지 않을까 싶습니다
201번 코드는 요청이 성공적으로 이루어졌고 새로운 리소스가 생성되었다는 의미입니다

그 외에 다른 http 상태 코드들도 유념해주시길 바라겠습니다~

**Comment by dntjd960403** [comment]
세세하게 바꿔 봤습니다!!!!!!!
